### ISSUE TITLE
Adding Adastra support

### ISSUE THREAD

**Issue by etiennemlb** [idriscnrs/idr_torch#1]
Would it be possible to implement support for Adastra's SLURM configuration ?

**Comment by RemiLacroix-IDRIS** [comment]
Hello. It might work already since the SLURM bits of the code are not specific to IDRIS. Are you facing a specific issue?

**Comment by etiennemlb** [comment]
I used the /idr_accelerate/examples/multi-node/train_accelerate.py. The issue my very well be due to `idr_accelerate` more than ird_torch.

In the few tests I did, I observed that only one of the 8 GPUs of a node where being used. Although it was spawning 4 sub processes.

**Comment by RemiLacroix-IDRIS** [comment]
If you print `idr_torch.gpu_ids` from that job, what do you get?

**Comment by etiennemlb** [comment]
Yep, it was empty. By default, when you do not specify something like `gpus-per-task=8` on Adastra, the `SLURM_STEP_GPUS` environment variable is not populated and the idr_accelerate wrapper does not like that.

**Comment by RemiLacroix-IDRIS** [comment]
Yes, the idr_accelerate wrapper uses the GPU ids so you have to explicitly requests some GPUs in Slurm.
